### ISSUE TITLE
ファイルの種類ごとにアップロードサイズ制限を設ける

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#351]
現在はファイルの種類に関係なくサイズを制限することができる。
```
# config/environment.yml
max_filesize: 104857600
```

**Comment by tany** [comment]
拡張子ごとにファイルサイズを設定する。
```
# config/environment.yml
max_filesize_ext:
  bmp:
  doc:
  docx:
  flv:
  gif:
  jpg:
  jpeg:
  mp3:
  mp4:
  pdf:
  png:
  ppt:
  pptx:
  wmv:
  xls:
  xlsx:
```
